# Generated by Django 5.2.17 on 2026-08-18 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawljob',
            name='trigger_type',
            field=models.CharField(blank=True, choices=[('SCHEDULED', '스케줄'), ('MANUAL', '수동'), ('RETRY', '재시도'), ('BACKFILL', '과거 데이터 수집')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='BackfillBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', '준비'), ('PENDING', '대기'), ('RUNNING', '진행중'), ('SUCCESS', '완료'), ('PARTIAL', '부분완료'), ('FAILED', '실패')], default='DRAFT', max_length=20)),
                ('start_month', models.DateField()),
                ('end_month', models.DateField()),
                ('gender_codes', models.JSONField(default=list)),
                ('category_codes', models.JSONField(default=list)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('success_items', models.PositiveIntegerField(default=0)),
                ('failed_items', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backfill_batches', to='crawler.source')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackfillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=6)),
                ('gender_code', models.CharField(max_length=10)),
                ('category_code', models.CharField(max_length=20)),
                ('request_url', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('RUNNING', '진행중'), ('SUCCESS', '성공'), ('FAILED', '실패')], default='PENDING', max_length=20)),
                ('items_found', models.PositiveIntegerField(default=0)),
                ('items_created', models.PositiveIntegerField(default=0)),
                ('items_updated', models.PositiveIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_type', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crawler.backfillbatch')),
                ('crawl_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backfill_item', to='crawler.crawljob')),
            ],
            options={
                'ordering': ['year_month', 'gender_code', 'category_code'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'year_month', 'gender_code', 'category_code'), name='unique_backfill_item')],
            },
        ),
    ]
