# Generated by Django 5.2.17 on 2026-08-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_alter_crawljob_trigger_type_backfillbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubecreator',
            name='uploads_playlist_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
