# Generated by Django 5.2.17 on 2026-08-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0003_youtubecreator_uploads_playlist_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubecreator",
            name="last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="youtubecreator",
            name="last_video_id",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
