# Generated by Django 6.0.8 on 2026-08-20 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0004_youtubecreator_last_checked_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZigzagStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_store_id", models.CharField(max_length=200, unique=True)),
                ("store_name", models.CharField(db_index=True, max_length=300)),
                ("is_brand", models.BooleanField(default=False)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="backfillbatch",
            options={},
        ),
        migrations.AlterModelOptions(
            name="backfillitem",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="backfillitem",
            name="unique_backfill_item",
        ),
        migrations.RemoveIndex(
            model_name="zigzagproduct",
            name="crawler_zig_store_i_b3e792_idx",
        ),
        migrations.RemoveIndex(
            model_name="zigzagproduct",
            name="crawler_zig_store_n_90c807_idx",
        ),
        migrations.RemoveIndex(
            model_name="zigzagproduct",
            name="crawler_zig_brand_n_db7839_idx",
        ),
        migrations.RenameField(
            model_name="backfillbatch",
            old_name="end_month",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="backfillbatch",
            old_name="start_month",
            new_name="start_date",
        ),
        migrations.RemoveField(
            model_name="backfillbatch",
            name="category_codes",
        ),
        migrations.RemoveField(
            model_name="backfillbatch",
            name="gender_codes",
        ),
        migrations.AddField(
            model_name="backfillbatch",
            name="params",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="backfillitem",
            name="params",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="backfillitem",
            name="target_key",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name="backfillbatch",
            name="status",
            field=models.CharField(db_index=True, default="PENDING", max_length=30),
        ),
        migrations.AlterField(
            model_name="backfillitem",
            name="request_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="backfillitem",
            name="status",
            field=models.CharField(db_index=True, default="PENDING", max_length=30),
        ),
        migrations.AddIndex(
            model_name="zigzagstore",
            index=models.Index(
                fields=["store_name"], name="crawler_zig_store_n_352245_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="zigzagstore",
            index=models.Index(
                fields=["is_brand"], name="crawler_zig_is_bran_9b4f55_idx"
            ),
        ),
        # 기존 CharField store_id 먼저 제거
        migrations.RemoveField(
            model_name="zigzagproduct",
            name="store_id",
        ),
        # 새 ForeignKey store 추가
        # DB 컬럼명은 자동으로 store_id가 됨
        migrations.AddField(
            model_name="zigzagproduct",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="crawler.zigzagstore",
            ),
        ),
        migrations.AddIndex(
            model_name="zigzagproduct",
            index=models.Index(fields=["store"], name="crawler_zig_store_i_b3e792_idx"),
        ),
        migrations.RemoveField(
            model_name="backfillitem",
            name="category_code",
        ),
        migrations.RemoveField(
            model_name="backfillitem",
            name="gender_code",
        ),
        migrations.RemoveField(
            model_name="backfillitem",
            name="year_month",
        ),
        migrations.RemoveField(
            model_name="zigzagproduct",
            name="brand_name",
        ),
        migrations.RemoveField(
            model_name="zigzagproduct",
            name="store_name",
        ),
    ]
