# Generated by Django 6.0.8 on 2026-08-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_zigzagstore_alter_backfillbatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musinsaproductsnapshot',
            name='ranking_age_band',
            field=models.CharField(blank=True, db_index=True, help_text='랭킹 연령대 기준 (ex. AGE_BAND_ALL, AGE_BAND_MINOR)', max_length=50, null=True),
        ),
    ]
