# Generated by Django 6.1 on 2026-09-16 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_contentitem_ad_disclosure_contentitem_content_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_review_id', models.CharField(max_length=100)),
                ('review_type', models.CharField(blank=True, default='', max_length=30)),
                ('content', models.TextField()),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('goods_option', models.CharField(blank=True, default='', max_length=200)),
                ('like_count', models.IntegerField(default=0)),
                ('reviewer_sex', models.CharField(blank=True, default='', max_length=20)),
                ('reviewer_height', models.IntegerField(blank=True, null=True)),
                ('reviewer_weight', models.IntegerField(blank=True, null=True)),
                ('survey', models.JSONField(blank=True, default=dict)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.productsource')),
            ],
            options={
                'db_table': '"commerce"."product_review"',
                'constraints': [models.UniqueConstraint(fields=('product_source', 'source_review_id'), name='uq_product_review_source_review')],
            },
        ),
    ]
